name: .NET Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        dotnet-version: [ '8.0.x' ]
    timeout-minutes: 10
    
    services:
      kurrent:
        image: docker.kurrent.io/kurrent-latest/kurrentdb:25.0.1
        env:
          KURRENTDB_CLUSTER_SIZE: 1
          KURRENTDB_RUN_PROJECTIONS: All
          KURRENTDB_START_STANDARD_PROJECTIONS: true
          KURRENTDB_INSECURE: true
          KURRENTDB_ENABLE_ATOM_PUB_OVER_HTTP: true
        ports:
          - 2113:2113

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-restore --no-build --verbosity normal
